server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: window
          uri: http://localhost:8082
          predicates:
            - Path=/windows/**, 
        - id: work
          uri: http://localhost:8083
          predicates:
            - Path=/works/**, 
        - id: email
          uri: http://localhost:8084
          predicates:
            - Path=/emails/**, 
        - id: customer
          uri: http://localhost:8085
          predicates:
            - Path=, /myPages/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: window
          uri: http://window:8080
          predicates:
            - Path=/windows/**, 
        - id: work
          uri: http://work:8080
          predicates:
            - Path=/works/**, 
        - id: email
          uri: http://email:8080
          predicates:
            - Path=/emails/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
